server:
  port: 9000

spring:
  application:
    name: auth-server

app:
  ldap:
    url: ldap://localhost:389
    base-dn: dc=example,dc=org
    user-dn-pattern: uid={0},ou=people
    manager-dn: cn=admin,dc=example,dc=org
    manager-password: admin


